/**
 * Client-side receipt image handling.
 *
 * Validates a chosen file against the image types Mergepay accepts and
 * enforces a sensible size ceiling, then compresses large images in the
 * browser (via a hidden <canvas>) before anything is uploaded. Compression is
 * lossy for photographic content but keeps receipts legible while shrinking
 * a storage-heavy snapshot dramatically.
 *
 * Pure helpers (`formatBytes`, `validateReceiptFile`, `chooseCompressionTarget`)
 * are exported separately so they can be unit-tested without a DOM.
 */

/** The only image MIME types accepted for receipts. */
export const RECEIPT_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
] as const;

export type ReceiptMimeType = (typeof RECEIPT_MIME_TYPES)[number];

/** Human-friendly extensions for the accept hint and error messages. */
export const RECEIPT_EXTENSIONS = ["JPG", "PNG", "WEBP"] as const;

/**
 * Allowed file size, in bytes. 10 MB keeps phone snapshots and screenshots
 * welcome while bounding upload/storage costs.
 */
export const MAX_RECEIPT_BYTES = 10 * 1024 * 1024;

/**
 * Downscale target for the longest edge of an image, in pixels. Receipt text
 * stays readable at this resolution while file size drops sharply.
 */
export const MAX_RECEIPT_DIMENSION = 1600;

/**
 * JPEG is universally decoded, small, and perfect for photographic receipts;
 * it is used for every compressed output regardless of the source format.
 */
export const COMPRESS_MIME_TYPE = "image/jpeg";
export const COMPRESS_MIME_EXTENSION = "jpg";

/** Re-encode quality passed to `canvas.toBlob`. 0.82 balances size/legibility. */
export const COMPRESS_QUALITY = 0.82;

/** Length of the opaque id generated by the browser for the compressed file. */
const RANDOM_ID_LENGTH = 8;

/**
 * True when the file's MIME type is one Mergepay accepts for receipts.
 * Accepts `File` or a bare { type } so callers can validate cheaply before
 * touching the payload.
 */
export function isReceiptFile(file: { type: string }): boolean {
  return (RECEIPT_MIME_TYPES as readonly string[]).includes(file.type);
}

/** Human-readable size, e.g. `10 MB`, for error messages. */
export function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return "0 B";
  const units = ["B", "KB", "MB", "GB"];
  const i = Math.min(
    units.length - 1,
    Math.floor(Math.log(bytes) / Math.log(1024))
  );
  const value = bytes / Math.pow(1024, i);
  const rounded = value % 1 === 0 ? String(value) : value.toFixed(1);
  return `${rounded} ${units[i]}`;
}

export interface ReceiptFileError {
  ok: false;
  code: "unsupported_type" | "too_large";
  message: string;
}

export interface ReceiptFileValid {
  ok: true;
}

export type ReceiptFileValidation = ReceiptFileError | ReceiptFileValid;

/**
 * Bookkeeping about a decoded image so the caller can decide (and show)
 * whether compression will shrink anything.
 */
export interface ReceiptImageInfo {
  width: number;
  height: number;
  /** True when the image is bigger than the downscale target. */
  needsDownscale: boolean;
}

/**
 * Validate type and size before doing any heavier work. Type is checked
 * first so a 5 MB .exe doesn't get a size complaint about a format we would
 * reject anyway.
 */
export function validateReceiptFile(file: { type: string; size: number }): ReceiptFileValidation {
  if (!isReceiptFile(file)) {
    return {
      ok: false,
      code: "unsupported_type",
      message: `Please choose ${RECEIPT_EXTENSIONS.join(", ")} — other formats aren't supported for receipts.`,
    };
  }
  if (file.size > MAX_RECEIPT_BYTES) {
    return {
      ok: false,
      code: "too_large",
      message: `That image is ${formatBytes(file.size)} — receipts must be under ${formatBytes(MAX_RECEIPT_BYTES)}.`,
    };
  }
  return { ok: true };
}

/**
 * When an image is wider or taller than the MAX_RECEIPT_DIMENSION, how much a
 * re-encode to JPEG at COMPRESS_QUALITY is expected to save. Used to advertise
 * compression before the (slightly expensive) decode runs.
 */
export function chooseCompressionTarget(info: ReceiptImageInfo): {
  doCompress: boolean;
  targetWidth: number;
  targetHeight: number;
} {
  const longest = Math.max(info.width, info.height);
  if (longest <= MAX_RECEIPT_DIMENSION) {
    // Already fits; only compress when it's likely to be larger than a
    // reasonable re-encode.
    return {
      doCompress: true,
      targetWidth: info.width,
      targetHeight: info.height,
    };
  }
  const scale = MAX_RECEIPT_DIMENSION / longest;
  return {
    doCompress: true,
    targetWidth: Math.max(1, Math.round(info.width * scale)),
    targetHeight: Math.max(1, Math.round(info.height * scale)),
  };
}

/** Decode an Image from a Blob URL, resolving with its dimensions. */
function decodeImage(url: string): Promise<ReceiptImageInfo> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () =>
      resolve({
        width: img.naturalWidth,
        height: img.naturalHeight,
        needsDownscale:
          Math.max(img.naturalWidth, img.naturalHeight) > MAX_RECEIPT_DIMENSION,
      });
    img.onerror = () => reject(new Error("Could not read this image."));
    img.src = url;
  });
}

/**
 * Load a `File`, compress it with a hidden <canvas>, and return a new `File`
 * ready for upload. When the source is already an acceptable size and
 * dimension the original is returned (avoids a pointless re-encode).
 *
 * Returns `File` — an uploadable surface — or `Error` for unreadable images.
 */
export async function compressReceiptImage(
  file: File
): Promise<File> {
  const info = await readImageInfo(file);
  const { targetWidth, targetHeight } = chooseCompressionTarget(info);

  // Nothing to gain from a downscale re-encode: hand back the original.
  if (
    info.width === targetWidth &&
    info.height === targetHeight &&
    file.size <= MAX_RECEIPT_BYTES
  ) {
    return file;
  }

  const bitmap = await createImageBitmap(file).catch(() => null);
  if (!bitmap) {
    // ImageBitmap is unavailable/supported but the image did decode via <img>;
    // fall back to a canvas draw from that decoded source.
    return compressViaCanvas(file, targetWidth, targetHeight);
  }

  try {
    const canvas = document.createElement("canvas");
    canvas.width = targetWidth;
    canvas.height = targetHeight;
    const ctx = canvas.getContext("2d");
    if (!ctx) {
      bitmap.close();
      return file;
    }
    ctx.fillStyle = "#FFFFFF";
    ctx.fillRect(0, 0, targetWidth, targetHeight);
    ctx.drawImage(bitmap, 0, 0, targetWidth, targetHeight);
    bitmap.close();

    const blob = await canvasToBlob(canvas);
    if (!blob) return file;
    return new File([blob], renamedCompressedFile(file), {
      type: COMPRESS_MIME_TYPE,
    });
  } catch {
    bitmap.close();
    return file;
  }
}

/** Fallback path for runtimes without `createImageBitmap` (some Safari). */
function compressViaCanvas(
  file: File,
  targetWidth: number,
  targetHeight: number
): Promise<File> {
  return new Promise((resolve) => {
    const objectUrl = URL.createObjectURL(file);
    const img = new Image();
    img.onload = () => {
      try {
        const canvas = document.createElement("canvas");
        canvas.width = targetWidth;
        canvas.height = targetHeight;
        const ctx = canvas.getContext("2d");
        if (!ctx) {
          URL.revokeObjectURL(objectUrl);
          resolve(file);
          return;
        }
        ctx.fillStyle = "#FFFFFF";
        ctx.fillRect(0, 0, targetWidth, targetHeight);
        ctx.drawImage(img, 0, 0, targetWidth, targetHeight);
        URL.revokeObjectURL(objectUrl);
        void canvasToBlob(canvas).then((blob) => {
          resolve(
            blob
              ? new File([blob], renamedCompressedFile(file), {
                  type: COMPRESS_MIME_TYPE,
                })
              : file
          );
        });
      } catch {
        URL.revokeObjectURL(objectUrl);
        resolve(file);
      }
    };
    img.onerror = () => {
      URL.revokeObjectURL(objectUrl);
      resolve(file);
    };
    img.src = objectUrl;
  });
}

/** Read an image's natural dimensions via a hidden <img>. */
async function readImageInfo(file: File): Promise<ReceiptImageInfo> {
  const objectUrl = URL.createObjectURL(file);
  try {
    return await decodeImage(objectUrl);
  } finally {
    URL.revokeObjectURL(objectUrl);
  }
}

/** `canvas.toBlob` also wrapped in a Promise. */
function canvasToBlob(canvas: HTMLCanvasElement): Promise<Blob | null> {
  return new Promise((resolve) => canvas.toBlob(resolve, COMPRESS_MIME_TYPE, COMPRESS_QUALITY));
}

/** Give the compressed file a `-compressed` suffix, keeping it visually distinct. */
function renamedCompressedFile(file: File): string {
  const base = file.name.replace(/\.[^.]+$/, "") || "receipt";
  return `${base}-${randomId()}.${COMPRESS_MIME_EXTENSION}`;
}

/** Short random suffix so uploaded names don't collide. */
function randomId(): string {
  const bytes = new Uint8Array(RANDOM_ID_LENGTH);
  if (typeof crypto !== "undefined" && "getRandomValues" in crypto) {
    crypto.getRandomValues(bytes);
  }
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return typeof crypto !== "undefined" && "getRandomValues" in crypto
    ? hex
    : String(Date.now().toString(36));
}

/**
 * End-to-end pipeline used by the uploader: validate type/size, compress the
 * image, and hand back the file ready for `api.uploadReceipt`. Throws a
 * `ReceiptFileError`-shaped object (having `code` + `message`) on validation
 * failure so callers can render / toast the message.
 */
export async function prepareReceiptFile(
  file: File
): Promise<{ file: File; original: { size: number; name: string }; compressed: boolean }> {
  const validation = validateReceiptFile(file);
  if (!validation.ok) {
    throw { code: validation.code, message: validation.message };
  }
  const compressed = await compressReceiptImage(file);
  return {
    file: compressed,
    original: { size: file.size, name: file.name },
    compressed: compressed !== file,
  };
}